### ISSUE TITLE
Fire fox on linux detects as Chrome

### ISSUE THREAD

**Issue by idzivinskyi** [HaraldWalker/user-agent-utils#102]
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0 (Chrome)
Expected: "LINUX", "FIREFOX", "10.0"
Actual: "LINUX", "CHROME", null

**Comment by HaraldWalker** [comment]
Any idea why Firefox uses 'Chrome' in the string? Is that the name of a certain theme or interface?

**Comment by sampov2** [comment]
Evidence seems to point to this being an isolated issue with just this particular (quite old) version of Firefox.

I just checked a database of known user agent strings. It finds entries for "Firefox/10.0 (Chrome)", but not "Firefox/9.0 (Chrome)" or "Firefox/11.0 (Chrome)".

See http://id.furud.net/showdb.php?filter=Firefox%2F10.0+%28Chrome%29

For completeness sake, it's probably a good idea to recognize this browser correctly, but unless there's evidence that any other version than 10.0 shows up as (Chrome), it's probably a good idea to only match this particular version.

**Comment by HaraldWalker** [comment]
Right, what kind of Firefox is that? Current version on Linux is 38. 
This library has no intention to detect every possible (and old) version.

**Comment by sampov2** [comment]
According to Wikipedia, FF 10 is from January 2012 (https://en.wikipedia.org/wiki/History_of_Firefox#Version_10_.28ESR.29). That's still semi-recent when you consider use cases like analyzing past server logs.
