### ISSUE TITLE
Microsoft Edge browser support fails to parse version info

### ISSUE THREAD

**Issue by dmdabbs** [HaraldWalker/user-agent-utils#113]
I see the bug in parsing the Edge version info. The version parsing regexp incorrectly escaped the backslashes:

"(?:Edge\\\\/((12)\\\\.([0-9]*)))"
should be
"(?:Edge\\/((12)\\.([0-9]*)))"

Also note that the UA string used to test doesn't match what's seen in the wild:

Used to test:
Mozilla/5.0 (Windows NT 6.4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Edge/12.0

In the wild:
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

Fortunately, the Windows_10 OS parser added 6.4 as an alias. But you might consider putting the "NT 10" alias first in the list. . . .

new String[] { "Windows NT 6.4", "Windows NT 10" }

**Comment by dmdabbs** [comment]
Note that I think GitHub munched my string escapes. You will see it as soon as you look at the code. Four backslashes in the Edge version regexp versus two.

**Comment by dmdabbs** [comment]
FWIW, here is a UA string from our web logs today:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by cvnmlr** [comment]
I can verify that removing two backslashes (from four to two as above) makes the getBrowserVersion() work correctly on EDGE.

**Comment by HaraldWalker** [comment]
Fixed in #114 and available in the latest 1.18-SNAPSHOT release.
