### ISSUE TITLE
Edge Brower Version reporting Chrome version

### ISSUE THREAD

**Issue by malcolm-edgar** [HaraldWalker/user-agent-utils#122]
Testing with Release 1.17 with the Microsoft Edge browser is reporting the Chrome browser version (42) rather than the Edge version (12)

The submitted user agent was:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10532

**Comment by HaraldWalker** [comment]
This string passes the 1.18 tests. If you need it you could use the snasphot release.

**Comment by malcolm-edgar** [comment]
Thank you for the fix, much appreciated.
