### ISSUE TITLE
Code calls a lot of toLowerCase, very affect performance

### ISSUE THREAD

**Issue by melin** [HaraldWalker/user-agent-utils#123]
Code calls a lot of toLowerCase, very affect performance

public boolean isInUserAgentString(String agentString)
	{
    if (agentString == null) return false;

    String agentStringLowerCase = agentString.toLowerCase();
		for (String alias : aliases)
		{
      if (agentStringLowerCase.contains(alias))
				return true;
		}
		return false;
	}

**Comment by HaraldWalker** [comment]
In contrary. It only converts user agent string to lower case once. 
Are you using isInUserAgentString a lot? That method is intended for a single check and has to convert to lower case in that case.
