### ISSUE TITLE
Netscape broswers not detected

### ISSUE THREAD

**Issue by GokulakannanG** [HaraldWalker/user-agent-utils#124]
Here is my UserAgent string "Mozilla/5.0 (Windows; U; Win 9x 4.90; SG; rv:1.9.2.4) Gecko/20101104 Netscape/9.1.0285" 
But, it returns browser "MOZILLA"

But Actualy my browser is Netscape

**Comment by HaraldWalker** [comment]
An ancient browser that was discontinued 7 years ago without any market share today. Offers no business value to add detection for it.
