### ISSUE TITLE
FreeBSD OperatingSystem not supported

### ISSUE THREAD

**Issue by GokulakannanG** [HaraldWalker/user-agent-utils#127]
userstring from FreeBSD operating systems, useragentutils returns unknown for operatingsystem.

useragent string is "Mozilla/5.0 (X11; FreeBSD amd64; rv:26.0) Gecko/20100101 Firefox/26.0".
Another one userstring is "Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36"

its FreeBSD os. But, parser returns as unknown os... could you please check it?

**Comment by HaraldWalker** [comment]
FreeBSD is hardly ever being used by browsers (less than 0.01%). Not enough business value to detect it.
