### ISSUE TITLE
Maxthon browser not detected

### ISSUE THREAD

**Issue by GokulakannanG** [HaraldWalker/user-agent-utils#128]
Useragent String is "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Maxthon/4.5.2"

It detects Maxthon browser as AppleWebKit browser

**Comment by HaraldWalker** [comment]
Please read the FAQ. Maxthon browser as basically no noticeable market share.
