### ISSUE TITLE
MAC_OS_X_IPHONE not detectable for Opera user agents

### ISSUE THREAD

**Issue by katz12** [HaraldWalker/user-agent-utils#142]
Correct me if I'm wrong, but I believe the way the OS nesting works is that a user agent needs to match the parent before it can match the child.

For [MAC_OS_X_IPHONE](https://github.com/HaraldWalker/user-agent-utils/blob/trunk/src/main/java/eu/bitwalker/useragentutils/OperatingSystem.java#L125) under IOS, the "iPhone" string won't be checked unless the full "iPhone OS" string is present. Take a look at this user agent that I am seeing a fair amount of requests from:

`Opera/9.80 (iPhone; Opera Mini/7.0.5/37.6116; U; en) Presto/2.12.423 Version/12.16`

I think it's pretty obvious that this should be an iPhone.

What do you think?

**Comment by HaraldWalker** [comment]
Yes, and all other iOS user agents so far follow the pattern to include ' like Mac OS X' in the user-agent string. Opera is a real PITA lately. Previously they used "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Coast/1.0.2.62956 Mobile/10B329 Safari/7534.48.3 " for the Opera Coast version of their browser. 
Changing "iPhone OS" to ""iPhone" in the parent should be safe and fix this issue.

**Comment by katz12** [comment]
Great! Should make a patch then?

**Comment by HaraldWalker** [comment]
Since I have it open right now, I'll directly change it now and then make a snapshot release.

**Comment by katz12** [comment]
Thanks!

**Comment by HaraldWalker** [comment]
Since Opara Mini does not include any useful details about the actual iOS version it will now detect it as MAC_OS_X_IPHONE (first iPhones did not use the term iOS) but at least it is a child of the iOS group.

**Comment by katz12** [comment]
Hey, I don't mean to be a nag but when do you usually decide to make a new release? After a certain amount of issues are resolved?

I attempted to pull in the 1.20-SNAPSHOT release to get this change but it doesn't seem to be available on maven: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22eu.bitwalker%22%20AND%20a%3A%22UserAgentUtils%22
