### ISSUE TITLE
Make Browser's constructor public

### ISSUE THREAD

**Issue by ksrichard** [HaraldWalker/user-agent-utils#143]
could you please make the Browser enum's constructor public?
it adds the possibility to add new browsers without any big modifications

**Comment by alexradzin** [comment]
It is impossible because `Browser` is `enum`.

**Comment by ksrichard** [comment]
I would like to only make the Browser enum's constructor public

**Comment by ksrichard** [comment]
private Browser(...) should be public

**Comment by HaraldWalker** [comment]
http://docs.oracle.com/javase/tutorial/java/javaOO/enum.html

> The constructor for an enum type must be package-private or private access. It automatically creates the constants that are defined at the beginning of the enum body. You cannot invoke an enum constructor yourself.
