### ISSUE TITLE
getBrowserVersion is null for IEMobile/11.0

### ISSUE THREAD

**Issue by ujay68** [HaraldWalker/user-agent-utils#69]
On Windows Phone 8.1 with IE 11, eu.bitwalker.useragentutils.UserAgent.getBrowserVersion() returns null.

```
User-Agent: Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 930) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537
```

**Comment by waded** [comment]
The javadoc appears to be correct (states that getBrowserVersion() will return null when version can't be determined), so thanks for that!

This article provides guidance on how to parse browser version for IE starting with IE11. http://msdn.microsoft.com/en-us/library/ie/bg182625(v=vs.85).aspx#uaString 

Briefly: "The version of the browser is now reported by a new revision ("rv") token."
