### ISSUE TITLE
Wrong platform shown for IOS 8.3 for both Chrome and Safari

### ISSUE THREAD

**Issue by rio2311** [HaraldWalker/user-agent-utils#85]
Instead of showing platform IOS 8.3, following platform was used: Mac OS X(iPhone), which is confusing

Browsers used:
Latest Chrome for iOS;
Latest Safari on iOS 8.3.

User-agents provided:
Chrome Mobile:
Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/41.0.2272.58 Mobile/12F70 Safari/600.1.4

Safari Mobile:
Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4

**Comment by HaraldWalker** [comment]
Inflation of version numbers is going fast again. We only had support until 8.1. Usually Apple didn't need extra versions for minor versions. Usually I would just detect them all as iOS 8 and ignore the rest but if was with 8.1 that apple introduced some new features. Guess now I will also have to detect 8.3.
