### ISSUE TITLE
Opera Mobile for Android 4.x was recognized as Chrome mobile

### ISSUE THREAD

**Issue by rio2311** [HaraldWalker/user-agent-utils#86]

**Comment by rio2311** [comment]
Mozilla/5.0 (Linux; Android 4.1.2; HTC One SV Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.81 Mobile Safari/537.36 OPR/28.0.1764.90386 - This UA was recognized as Chrome Mobile, instead of latest Opera Mobile for Android

**Comment by HaraldWalker** [comment]
I've added opera mobile as new type even tough opera officially doesn't seem to use it. In total they have 4 different mobile browsers now.
